server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net:3306/heroku_1e63af74e36449c?useUnicode=yes&characterEncoding=UTF-8
    username: be6220aec8fad6
    password: c4cd6ae5
    tomcat:
      max-wait: 20000
      max-active: 100
      max-idle: 20
      min-idle: 15
  jpa:
    properties:
      hibernate:
        format_sql: true
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
      show-sql: false